Fixed xskipper rule extension doc
xskipper-io/xskipper pull request #97
Opened 2022-01-24 11:03 UTC by oshritf

### What changes are proposed in this pull request?
Fixed xskipper rule documentation: class name and usage

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Not relevant

2022-01-24 14:29 UTC, guykhazma requested changes
Can you please add details to the site as well

2022-01-24 14:29 UTC, guykhazma commented on src/main/scala/io/xskipper/utils/RuleExtension.scala
> +  *    Alternatively, instead of --jars use --packages io.xskipper:xskipper-coreX:Y
why `X:Y` here?

2022-01-24 16:09 UTC, oshritf commented on src/main/scala/io/xskipper/utils/RuleExtension.scala
> +  *    Alternatively, instead of --jars use --packages io.xskipper:xskipper-coreX:Y
scala version, release version

2022-01-25 14:46 UTC, guykhazma approved these changes
LGTM 
some comments

2022-01-25 14:46 UTC, guykhazma commented on site/docs/getting-started/quick-start-guide.md
> +Xskipper also provides an API to inject the DataSkippingFileIndexRule into catalyst as part of the operatorOptimization rules and enable it using spark session extensions injectOptimizerRule.
please wrap DataSkippingFileIndexRule with backticks.

2022-01-25 14:46 UTC, guykhazma commented on site/docs/getting-started/quick-start-guide.md
> +    ```
please add bash here so it will use the right highlighting.
so:
```
``` bash
```

2022-01-25 14:46 UTC, guykhazma commented on site/docs/getting-started/quick-start-guide.md
> +By adding io.xskipper.utils.RuleExtension to spark.sql.extensions Xskipper optimization rules become visible to the Apache Spark optimizer and will be used in query optimization and execution.
same for `io.xskipper.utils.RuleExtension`

2022-01-25 17:29 UTC, merged